# Generated by Django 6.0.5 on 2026-05-23 18:34

import django.db.models.deletion
import nyondoapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15, validators=[nyondoapp.models.validate_ug_phone])),
                ('product_name', models.CharField(max_length=100)),
                ('nin', models.CharField(max_length=14, validators=[nyondoapp.models.validate_nin])),
                ('location', models.CharField(max_length=100)),
                ('total_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255, unique=True)),
                ('product_description', models.CharField(max_length=255)),
                ('amount_paid', models.IntegerField()),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('balance_remaining', models.IntegerField()),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('unit_cost', models.IntegerField()),
                ('current_stock', models.IntegerField(default=0)),
                ('threshold', models.IntegerField(default=10)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('wholesaler_rate', models.IntegerField(default=0)),
                ('wholesaler_price', models.IntegerField(default=0)),
                ('retailer_rate', models.IntegerField(default=0)),
                ('retailer_price', models.IntegerField(default=0)),
                ('normal_rate', models.IntegerField(default=0)),
                ('normal_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashier', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('distance', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField()),
                ('transport_fee', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('payment', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('TRN', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=15, validators=[nyondoapp.models.validate_ug_phone])),
                ('product_description', models.TextField()),
                ('payment_option', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_date', models.DateField(auto_now_add=True)),
                ('deposit_amount', models.IntegerField()),
                ('expected_completion', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Finished', 'Finished')], max_length=20)),
                ('product_name', models.CharField(choices=[('cement', 'cement'), ('iron sheets', 'iron sheets'), ('iron bars', 'iron bars')], max_length=100)),
                ('Customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyondoapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('sales_attendant', 'sales_attendant'), ('store_manager', 'store_manager')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('units', models.CharField(max_length=20)),
                ('unit_price', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='nyondoapp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Scredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amount_owed', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('overdue', 'overdue')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyondoapp.supplier')),
            ],
        ),
    ]
