# Generated by Django 6.0.5 on 2026-05-24 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricing',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nyondoapp.product'),
            preserve_default=False,
        ),
    ]
